### ISSUE TITLE
Module Matching does not always work

### ISSUE THREAD

**Issue by thestr4ng3r** [oddcoder/CutterDRcov#1]
[notepad-cov.tar.gz](https://github.com/oddcoder/CutterDRcov/files/3000423/notepad-cov.tar.gz)

Name from drcov is "C:\Windows\notepad.exe", Filename from r2 is "notepad.exe".
`getModuleIdx()` will not match them together and return None, which will lead to an exception:
```
Traceback (most recent call last):
  File "/home/florian/.local/share/RadareOrg/Cutter/plugins/python/CutterDRcov/cutterplugin.py", line 57, in dropFile
    self.loadcov(fileName)
  File "/home/florian/.local/share/RadareOrg/Cutter/plugins/python/CutterDRcov/cutterplugin.py", line 74, in loadcov
    analyse(self.config)
  File "/home/florian/.local/share/RadareOrg/Cutter/plugins/python/CutterDRcov/covTable.py", line 58, in analyse
    entry, hits = analyse_function(function, config['bbs'][idx])
TypeError: list indices must be integers or slices, not NoneType
```

**Comment by thestr4ng3r** [comment]
fixed by 3d66b3e27c7fbc71b65d3fb205d1d89953ddc7e6
